/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.masterdata.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.masterdata.model.Masterdata;
import io.jetprocess.masterdata.model.MasterdataModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Masterdata service. Represents a row in the &quot;Masterdata_Masterdata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterdataModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterdataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MasterdataImpl
 * @generated
 */
@JSON(strict = true)
public class MasterdataModelImpl
	extends BaseModelImpl<Masterdata> implements MasterdataModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a masterdata model instance should use the <code>Masterdata</code> interface instead.
	 */
	public static final String TABLE_NAME = "Masterdata_Masterdata";

	public static final Object[][] TABLE_COLUMNS = {
		{"masterdataId", Types.VARCHAR}, {"referenceId", Types.VARCHAR},
		{"value", Types.VARCHAR}, {"code_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("masterdataId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("referenceId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Masterdata_Masterdata (masterdataId VARCHAR(75) not null primary key,referenceId VARCHAR(75) null,value VARCHAR(75) null,code_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Masterdata_Masterdata";

	public static final String ORDER_BY_JPQL =
		" ORDER BY masterdata.masterdataId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Masterdata_Masterdata.masterdataId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MASTERDATAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MasterdataModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _masterdataId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setMasterdataId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _masterdataId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Masterdata.class;
	}

	@Override
	public String getModelClassName() {
		return Masterdata.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Masterdata, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Masterdata, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Masterdata, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Masterdata)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Masterdata, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Masterdata, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Masterdata)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Masterdata, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Masterdata, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Masterdata, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Masterdata, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Masterdata, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Masterdata, Object>>();
		Map<String, BiConsumer<Masterdata, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Masterdata, ?>>();

		attributeGetterFunctions.put(
			"masterdataId", Masterdata::getMasterdataId);
		attributeSetterBiConsumers.put(
			"masterdataId",
			(BiConsumer<Masterdata, String>)Masterdata::setMasterdataId);
		attributeGetterFunctions.put("referenceId", Masterdata::getReferenceId);
		attributeSetterBiConsumers.put(
			"referenceId",
			(BiConsumer<Masterdata, String>)Masterdata::setReferenceId);
		attributeGetterFunctions.put("value", Masterdata::getValue);
		attributeSetterBiConsumers.put(
			"value", (BiConsumer<Masterdata, String>)Masterdata::setValue);
		attributeGetterFunctions.put("code", Masterdata::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<Masterdata, String>)Masterdata::setCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getMasterdataId() {
		if (_masterdataId == null) {
			return "";
		}
		else {
			return _masterdataId;
		}
	}

	@Override
	public void setMasterdataId(String masterdataId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_masterdataId = masterdataId;
	}

	@JSON
	@Override
	public String getReferenceId() {
		if (_referenceId == null) {
			return "";
		}
		else {
			return _referenceId;
		}
	}

	@Override
	public void setReferenceId(String referenceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_referenceId = referenceId;
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Masterdata toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Masterdata>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterdataImpl masterdataImpl = new MasterdataImpl();

		masterdataImpl.setMasterdataId(getMasterdataId());
		masterdataImpl.setReferenceId(getReferenceId());
		masterdataImpl.setValue(getValue());
		masterdataImpl.setCode(getCode());

		masterdataImpl.resetOriginalValues();

		return masterdataImpl;
	}

	@Override
	public Masterdata cloneWithOriginalValues() {
		MasterdataImpl masterdataImpl = new MasterdataImpl();

		masterdataImpl.setMasterdataId(
			this.<String>getColumnOriginalValue("masterdataId"));
		masterdataImpl.setReferenceId(
			this.<String>getColumnOriginalValue("referenceId"));
		masterdataImpl.setValue(this.<String>getColumnOriginalValue("value"));
		masterdataImpl.setCode(this.<String>getColumnOriginalValue("code_"));

		return masterdataImpl;
	}

	@Override
	public int compareTo(Masterdata masterdata) {
		String primaryKey = masterdata.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Masterdata)) {
			return false;
		}

		Masterdata masterdata = (Masterdata)object;

		String primaryKey = masterdata.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Masterdata> toCacheModel() {
		MasterdataCacheModel masterdataCacheModel = new MasterdataCacheModel();

		masterdataCacheModel.masterdataId = getMasterdataId();

		String masterdataId = masterdataCacheModel.masterdataId;

		if ((masterdataId != null) && (masterdataId.length() == 0)) {
			masterdataCacheModel.masterdataId = null;
		}

		masterdataCacheModel.referenceId = getReferenceId();

		String referenceId = masterdataCacheModel.referenceId;

		if ((referenceId != null) && (referenceId.length() == 0)) {
			masterdataCacheModel.referenceId = null;
		}

		masterdataCacheModel.value = getValue();

		String value = masterdataCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			masterdataCacheModel.value = null;
		}

		masterdataCacheModel.code = getCode();

		String code = masterdataCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			masterdataCacheModel.code = null;
		}

		return masterdataCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Masterdata, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Masterdata, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Masterdata, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Masterdata)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Masterdata, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Masterdata, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Masterdata, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Masterdata)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Masterdata>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Masterdata.class, ModelWrapper.class);

	}

	private String _masterdataId;
	private String _referenceId;
	private String _value;
	private String _code;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Masterdata, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Masterdata)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("masterdataId", _masterdataId);
		_columnOriginalValues.put("referenceId", _referenceId);
		_columnOriginalValues.put("value", _value);
		_columnOriginalValues.put("code_", _code);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("code_", "code");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("masterdataId", 1L);

		columnBitmasks.put("referenceId", 2L);

		columnBitmasks.put("value", 4L);

		columnBitmasks.put("code_", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Masterdata _escapedModel;

}