/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.model.DocumentNoteMap;
import io.jetprocess.model.DocumentNoteMapModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DocumentNoteMap service. Represents a row in the &quot;JET_PROCESS_DocumentNoteMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DocumentNoteMapModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocumentNoteMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentNoteMapImpl
 * @generated
 */
@JSON(strict = true)
public class DocumentNoteMapModelImpl
	extends BaseModelImpl<DocumentNoteMap> implements DocumentNoteMapModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a document note map model instance should use the <code>DocumentNoteMap</code> interface instead.
	 */
	public static final String TABLE_NAME = "JET_PROCESS_DocumentNoteMap";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"documentNoteMapId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"noteDocumentId", Types.BIGINT}, {"noteId", Types.BIGINT},
		{"movementId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentNoteMapId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("noteDocumentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("noteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("movementId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JET_PROCESS_DocumentNoteMap (uuid_ VARCHAR(75) null,documentNoteMapId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,noteDocumentId LONG,noteId LONG,movementId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table JET_PROCESS_DocumentNoteMap";

	public static final String ORDER_BY_JPQL =
		" ORDER BY documentNoteMap.documentNoteMapId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JET_PROCESS_DocumentNoteMap.documentNoteMapId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOCUMENTNOTEMAPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DocumentNoteMapModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _documentNoteMapId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDocumentNoteMapId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _documentNoteMapId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DocumentNoteMap.class;
	}

	@Override
	public String getModelClassName() {
		return DocumentNoteMap.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DocumentNoteMap, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DocumentNoteMap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DocumentNoteMap, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DocumentNoteMap)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DocumentNoteMap, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DocumentNoteMap, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DocumentNoteMap)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DocumentNoteMap, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DocumentNoteMap, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<DocumentNoteMap, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DocumentNoteMap, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DocumentNoteMap, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<DocumentNoteMap, Object>>();
		Map<String, BiConsumer<DocumentNoteMap, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DocumentNoteMap, ?>>();

		attributeGetterFunctions.put("uuid", DocumentNoteMap::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<DocumentNoteMap, String>)DocumentNoteMap::setUuid);
		attributeGetterFunctions.put(
			"documentNoteMapId", DocumentNoteMap::getDocumentNoteMapId);
		attributeSetterBiConsumers.put(
			"documentNoteMapId",
			(BiConsumer<DocumentNoteMap, Long>)
				DocumentNoteMap::setDocumentNoteMapId);
		attributeGetterFunctions.put("groupId", DocumentNoteMap::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<DocumentNoteMap, Long>)DocumentNoteMap::setGroupId);
		attributeGetterFunctions.put(
			"companyId", DocumentNoteMap::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DocumentNoteMap, Long>)DocumentNoteMap::setCompanyId);
		attributeGetterFunctions.put("userId", DocumentNoteMap::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<DocumentNoteMap, Long>)DocumentNoteMap::setUserId);
		attributeGetterFunctions.put("userName", DocumentNoteMap::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DocumentNoteMap, String>)DocumentNoteMap::setUserName);
		attributeGetterFunctions.put(
			"createDate", DocumentNoteMap::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DocumentNoteMap, Date>)DocumentNoteMap::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DocumentNoteMap::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DocumentNoteMap, Date>)
				DocumentNoteMap::setModifiedDate);
		attributeGetterFunctions.put(
			"noteDocumentId", DocumentNoteMap::getNoteDocumentId);
		attributeSetterBiConsumers.put(
			"noteDocumentId",
			(BiConsumer<DocumentNoteMap, Long>)
				DocumentNoteMap::setNoteDocumentId);
		attributeGetterFunctions.put("noteId", DocumentNoteMap::getNoteId);
		attributeSetterBiConsumers.put(
			"noteId",
			(BiConsumer<DocumentNoteMap, Long>)DocumentNoteMap::setNoteId);
		attributeGetterFunctions.put(
			"movementId", DocumentNoteMap::getMovementId);
		attributeSetterBiConsumers.put(
			"movementId",
			(BiConsumer<DocumentNoteMap, Long>)DocumentNoteMap::setMovementId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getDocumentNoteMapId() {
		return _documentNoteMapId;
	}

	@Override
	public void setDocumentNoteMapId(long documentNoteMapId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentNoteMapId = documentNoteMapId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getNoteDocumentId() {
		return _noteDocumentId;
	}

	@Override
	public void setNoteDocumentId(long noteDocumentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noteDocumentId = noteDocumentId;
	}

	@JSON
	@Override
	public long getNoteId() {
		return _noteId;
	}

	@Override
	public void setNoteId(long noteId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noteId = noteId;
	}

	@JSON
	@Override
	public long getMovementId() {
		return _movementId;
	}

	@Override
	public void setMovementId(long movementId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_movementId = movementId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DocumentNoteMap.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DocumentNoteMap.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DocumentNoteMap toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DocumentNoteMap>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DocumentNoteMapImpl documentNoteMapImpl = new DocumentNoteMapImpl();

		documentNoteMapImpl.setUuid(getUuid());
		documentNoteMapImpl.setDocumentNoteMapId(getDocumentNoteMapId());
		documentNoteMapImpl.setGroupId(getGroupId());
		documentNoteMapImpl.setCompanyId(getCompanyId());
		documentNoteMapImpl.setUserId(getUserId());
		documentNoteMapImpl.setUserName(getUserName());
		documentNoteMapImpl.setCreateDate(getCreateDate());
		documentNoteMapImpl.setModifiedDate(getModifiedDate());
		documentNoteMapImpl.setNoteDocumentId(getNoteDocumentId());
		documentNoteMapImpl.setNoteId(getNoteId());
		documentNoteMapImpl.setMovementId(getMovementId());

		documentNoteMapImpl.resetOriginalValues();

		return documentNoteMapImpl;
	}

	@Override
	public DocumentNoteMap cloneWithOriginalValues() {
		DocumentNoteMapImpl documentNoteMapImpl = new DocumentNoteMapImpl();

		documentNoteMapImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		documentNoteMapImpl.setDocumentNoteMapId(
			this.<Long>getColumnOriginalValue("documentNoteMapId"));
		documentNoteMapImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		documentNoteMapImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		documentNoteMapImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		documentNoteMapImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		documentNoteMapImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		documentNoteMapImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		documentNoteMapImpl.setNoteDocumentId(
			this.<Long>getColumnOriginalValue("noteDocumentId"));
		documentNoteMapImpl.setNoteId(
			this.<Long>getColumnOriginalValue("noteId"));
		documentNoteMapImpl.setMovementId(
			this.<Long>getColumnOriginalValue("movementId"));

		return documentNoteMapImpl;
	}

	@Override
	public int compareTo(DocumentNoteMap documentNoteMap) {
		long primaryKey = documentNoteMap.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DocumentNoteMap)) {
			return false;
		}

		DocumentNoteMap documentNoteMap = (DocumentNoteMap)object;

		long primaryKey = documentNoteMap.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DocumentNoteMap> toCacheModel() {
		DocumentNoteMapCacheModel documentNoteMapCacheModel =
			new DocumentNoteMapCacheModel();

		documentNoteMapCacheModel.uuid = getUuid();

		String uuid = documentNoteMapCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			documentNoteMapCacheModel.uuid = null;
		}

		documentNoteMapCacheModel.documentNoteMapId = getDocumentNoteMapId();

		documentNoteMapCacheModel.groupId = getGroupId();

		documentNoteMapCacheModel.companyId = getCompanyId();

		documentNoteMapCacheModel.userId = getUserId();

		documentNoteMapCacheModel.userName = getUserName();

		String userName = documentNoteMapCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			documentNoteMapCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			documentNoteMapCacheModel.createDate = createDate.getTime();
		}
		else {
			documentNoteMapCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			documentNoteMapCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			documentNoteMapCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		documentNoteMapCacheModel.noteDocumentId = getNoteDocumentId();

		documentNoteMapCacheModel.noteId = getNoteId();

		documentNoteMapCacheModel.movementId = getMovementId();

		return documentNoteMapCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DocumentNoteMap, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DocumentNoteMap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DocumentNoteMap, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DocumentNoteMap)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DocumentNoteMap, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DocumentNoteMap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DocumentNoteMap, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DocumentNoteMap)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DocumentNoteMap>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DocumentNoteMap.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _documentNoteMapId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _noteDocumentId;
	private long _noteId;
	private long _movementId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DocumentNoteMap, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DocumentNoteMap)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("documentNoteMapId", _documentNoteMapId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("noteDocumentId", _noteDocumentId);
		_columnOriginalValues.put("noteId", _noteId);
		_columnOriginalValues.put("movementId", _movementId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("documentNoteMapId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("noteDocumentId", 256L);

		columnBitmasks.put("noteId", 512L);

		columnBitmasks.put("movementId", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DocumentNoteMap _escapedModel;

}