/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.model.NoteDocMovement;
import io.jetprocess.model.NoteDocMovementModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NoteDocMovement service. Represents a row in the &quot;JET_PROCESS_NoteDocMovement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NoteDocMovementModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NoteDocMovementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NoteDocMovementImpl
 * @generated
 */
@JSON(strict = true)
public class NoteDocMovementModelImpl
	extends BaseModelImpl<NoteDocMovement> implements NoteDocMovementModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a note doc movement model instance should use the <code>NoteDocMovement</code> interface instead.
	 */
	public static final String TABLE_NAME = "JET_PROCESS_NoteDocMovement";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"movementId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"receiverId", Types.BIGINT}, {"senderId", Types.BIGINT},
		{"noteDocumentId", Types.BIGINT}, {"remarks", Types.VARCHAR},
		{"active_", Types.BOOLEAN}, {"movementType", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("movementId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("receiverId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("senderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("noteDocumentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("remarks", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("movementType", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JET_PROCESS_NoteDocMovement (uuid_ VARCHAR(75) null,movementId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,receiverId LONG,senderId LONG,noteDocumentId LONG,remarks VARCHAR(500) null,active_ BOOLEAN,movementType LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table JET_PROCESS_NoteDocMovement";

	public static final String ORDER_BY_JPQL =
		" ORDER BY noteDocMovement.movementId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JET_PROCESS_NoteDocMovement.movementId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MOVEMENTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NoteDocMovementModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _movementId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMovementId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _movementId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NoteDocMovement.class;
	}

	@Override
	public String getModelClassName() {
		return NoteDocMovement.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NoteDocMovement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NoteDocMovement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NoteDocMovement, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NoteDocMovement)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NoteDocMovement, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NoteDocMovement, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NoteDocMovement)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NoteDocMovement, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NoteDocMovement, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<NoteDocMovement, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NoteDocMovement, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NoteDocMovement, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<NoteDocMovement, Object>>();
		Map<String, BiConsumer<NoteDocMovement, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NoteDocMovement, ?>>();

		attributeGetterFunctions.put("uuid", NoteDocMovement::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<NoteDocMovement, String>)NoteDocMovement::setUuid);
		attributeGetterFunctions.put(
			"movementId", NoteDocMovement::getMovementId);
		attributeSetterBiConsumers.put(
			"movementId",
			(BiConsumer<NoteDocMovement, Long>)NoteDocMovement::setMovementId);
		attributeGetterFunctions.put("groupId", NoteDocMovement::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<NoteDocMovement, Long>)NoteDocMovement::setGroupId);
		attributeGetterFunctions.put(
			"companyId", NoteDocMovement::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NoteDocMovement, Long>)NoteDocMovement::setCompanyId);
		attributeGetterFunctions.put("userId", NoteDocMovement::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<NoteDocMovement, Long>)NoteDocMovement::setUserId);
		attributeGetterFunctions.put("userName", NoteDocMovement::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<NoteDocMovement, String>)NoteDocMovement::setUserName);
		attributeGetterFunctions.put(
			"createDate", NoteDocMovement::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<NoteDocMovement, Date>)NoteDocMovement::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", NoteDocMovement::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<NoteDocMovement, Date>)
				NoteDocMovement::setModifiedDate);
		attributeGetterFunctions.put(
			"receiverId", NoteDocMovement::getReceiverId);
		attributeSetterBiConsumers.put(
			"receiverId",
			(BiConsumer<NoteDocMovement, Long>)NoteDocMovement::setReceiverId);
		attributeGetterFunctions.put("senderId", NoteDocMovement::getSenderId);
		attributeSetterBiConsumers.put(
			"senderId",
			(BiConsumer<NoteDocMovement, Long>)NoteDocMovement::setSenderId);
		attributeGetterFunctions.put(
			"noteDocumentId", NoteDocMovement::getNoteDocumentId);
		attributeSetterBiConsumers.put(
			"noteDocumentId",
			(BiConsumer<NoteDocMovement, Long>)
				NoteDocMovement::setNoteDocumentId);
		attributeGetterFunctions.put("remarks", NoteDocMovement::getRemarks);
		attributeSetterBiConsumers.put(
			"remarks",
			(BiConsumer<NoteDocMovement, String>)NoteDocMovement::setRemarks);
		attributeGetterFunctions.put("active", NoteDocMovement::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<NoteDocMovement, Boolean>)NoteDocMovement::setActive);
		attributeGetterFunctions.put(
			"movementType", NoteDocMovement::getMovementType);
		attributeSetterBiConsumers.put(
			"movementType",
			(BiConsumer<NoteDocMovement, Long>)
				NoteDocMovement::setMovementType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getMovementId() {
		return _movementId;
	}

	@Override
	public void setMovementId(long movementId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_movementId = movementId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getReceiverId() {
		return _receiverId;
	}

	@Override
	public void setReceiverId(long receiverId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_receiverId = receiverId;
	}

	@JSON
	@Override
	public long getSenderId() {
		return _senderId;
	}

	@Override
	public void setSenderId(long senderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_senderId = senderId;
	}

	@JSON
	@Override
	public long getNoteDocumentId() {
		return _noteDocumentId;
	}

	@Override
	public void setNoteDocumentId(long noteDocumentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noteDocumentId = noteDocumentId;
	}

	@JSON
	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return "";
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_remarks = remarks;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getMovementType() {
		return _movementType;
	}

	@Override
	public void setMovementType(long movementType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_movementType = movementType;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(NoteDocMovement.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NoteDocMovement.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NoteDocMovement toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NoteDocMovement>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NoteDocMovementImpl noteDocMovementImpl = new NoteDocMovementImpl();

		noteDocMovementImpl.setUuid(getUuid());
		noteDocMovementImpl.setMovementId(getMovementId());
		noteDocMovementImpl.setGroupId(getGroupId());
		noteDocMovementImpl.setCompanyId(getCompanyId());
		noteDocMovementImpl.setUserId(getUserId());
		noteDocMovementImpl.setUserName(getUserName());
		noteDocMovementImpl.setCreateDate(getCreateDate());
		noteDocMovementImpl.setModifiedDate(getModifiedDate());
		noteDocMovementImpl.setReceiverId(getReceiverId());
		noteDocMovementImpl.setSenderId(getSenderId());
		noteDocMovementImpl.setNoteDocumentId(getNoteDocumentId());
		noteDocMovementImpl.setRemarks(getRemarks());
		noteDocMovementImpl.setActive(isActive());
		noteDocMovementImpl.setMovementType(getMovementType());

		noteDocMovementImpl.resetOriginalValues();

		return noteDocMovementImpl;
	}

	@Override
	public NoteDocMovement cloneWithOriginalValues() {
		NoteDocMovementImpl noteDocMovementImpl = new NoteDocMovementImpl();

		noteDocMovementImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		noteDocMovementImpl.setMovementId(
			this.<Long>getColumnOriginalValue("movementId"));
		noteDocMovementImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		noteDocMovementImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		noteDocMovementImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		noteDocMovementImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		noteDocMovementImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		noteDocMovementImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		noteDocMovementImpl.setReceiverId(
			this.<Long>getColumnOriginalValue("receiverId"));
		noteDocMovementImpl.setSenderId(
			this.<Long>getColumnOriginalValue("senderId"));
		noteDocMovementImpl.setNoteDocumentId(
			this.<Long>getColumnOriginalValue("noteDocumentId"));
		noteDocMovementImpl.setRemarks(
			this.<String>getColumnOriginalValue("remarks"));
		noteDocMovementImpl.setActive(
			this.<Boolean>getColumnOriginalValue("active_"));
		noteDocMovementImpl.setMovementType(
			this.<Long>getColumnOriginalValue("movementType"));

		return noteDocMovementImpl;
	}

	@Override
	public int compareTo(NoteDocMovement noteDocMovement) {
		long primaryKey = noteDocMovement.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NoteDocMovement)) {
			return false;
		}

		NoteDocMovement noteDocMovement = (NoteDocMovement)object;

		long primaryKey = noteDocMovement.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NoteDocMovement> toCacheModel() {
		NoteDocMovementCacheModel noteDocMovementCacheModel =
			new NoteDocMovementCacheModel();

		noteDocMovementCacheModel.uuid = getUuid();

		String uuid = noteDocMovementCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			noteDocMovementCacheModel.uuid = null;
		}

		noteDocMovementCacheModel.movementId = getMovementId();

		noteDocMovementCacheModel.groupId = getGroupId();

		noteDocMovementCacheModel.companyId = getCompanyId();

		noteDocMovementCacheModel.userId = getUserId();

		noteDocMovementCacheModel.userName = getUserName();

		String userName = noteDocMovementCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			noteDocMovementCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			noteDocMovementCacheModel.createDate = createDate.getTime();
		}
		else {
			noteDocMovementCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			noteDocMovementCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			noteDocMovementCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		noteDocMovementCacheModel.receiverId = getReceiverId();

		noteDocMovementCacheModel.senderId = getSenderId();

		noteDocMovementCacheModel.noteDocumentId = getNoteDocumentId();

		noteDocMovementCacheModel.remarks = getRemarks();

		String remarks = noteDocMovementCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			noteDocMovementCacheModel.remarks = null;
		}

		noteDocMovementCacheModel.active = isActive();

		noteDocMovementCacheModel.movementType = getMovementType();

		return noteDocMovementCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NoteDocMovement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NoteDocMovement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NoteDocMovement, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((NoteDocMovement)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NoteDocMovement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NoteDocMovement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NoteDocMovement, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NoteDocMovement)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NoteDocMovement>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					NoteDocMovement.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _movementId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _receiverId;
	private long _senderId;
	private long _noteDocumentId;
	private String _remarks;
	private boolean _active;
	private long _movementType;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<NoteDocMovement, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NoteDocMovement)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("movementId", _movementId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("receiverId", _receiverId);
		_columnOriginalValues.put("senderId", _senderId);
		_columnOriginalValues.put("noteDocumentId", _noteDocumentId);
		_columnOriginalValues.put("remarks", _remarks);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("movementType", _movementType);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("movementId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("receiverId", 256L);

		columnBitmasks.put("senderId", 512L);

		columnBitmasks.put("noteDocumentId", 1024L);

		columnBitmasks.put("remarks", 2048L);

		columnBitmasks.put("active_", 4096L);

		columnBitmasks.put("movementType", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NoteDocMovement _escapedModel;

}