info:
    description: "JetProcessRS REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "JetProcessRS"
    version: v1.0
openapi: 3.0.1
components:
  schemas:
    ReceiptRsModel:
      description: Contains all the data for receipt creation.
      properties:
        receiptId:
          format: int64
          type: integer
        typeId:
          format: int64
          type: integer
        tempFileId:
          format: int64
          type: integer 
        groupId:
          format: int64
          type: integer
        deliveryModeId:
          format: int64
          type: integer
        receiptCategoryId:
          format: int64
          type: integer
        receiptSubCategoryId:
          format: int64
          type: integer
        countryId:
          format: int64
          type: integer
        stateId:
          format: int64
          type: integer
        organizationId:
          format: int64
          type: integer
        subOrganizationId:
          format: int64
          type: integer
        userPostId:
          format: int64
          type: integer
        receivedOn:
          type: string
        letterDate:
          type: string
        referenceNumber:
          type: string
        modeNumber:
          type: string
        subject:
          type: string
        remarks:
          type: string
        name:
          type: string
        designation:
          type: string
        mobile:
          type: string
        email:
          type: string
        address:
          type: string
        pinCode:
          type: string
        city:
          type: string
        viewPdfUrl:
          type: string
        dmFileId:
          format: int64
          type: integer
        receiptNumber:
          type: string  
        typevalue:
          type: string
        deliverymodevalue:
          type: string
        organizationvalue:
          type: string
        suborganizationvalue:
          type: string
        countryvalue:
          type: string
        statevalue:
          type: string
        receiptcategoryvalue:
          type: string
        receiptsubcategoryvalue:
          type: string 
        nature:
          type: string
        docFileId:
          format: int64
          type: integer
      type: object
    FileRsModel:
      description: Contains all the data for file creation.
      properties:
        id:
          format: int64
          type: integer
        nature:
          type: string
        type:
          type: string 
        groupId:
          format: int64
          type: integer
        basicHeadId:
          format: int64
          type: integer
        primaryHeadId:
          format: int64
          type: integer
        secondaryHeadId:
          format: int64
          type: integer
        tertiaryHeadId:
          format: int64
          type: integer
        year:
          format: int64
          type: integer
        fileCodeId:
          format: int64
          type: integer
        subject:
          type: string
        fileNumber:
          type: string
        categoryId:
          format: int64
          type: integer 
        subCategoryId:
          format: int64
          type: integer  
        remarks:
          type: string 
        reference:
          type: string 
        userPostId:
          format: int64
          type: integer   
        docFileId:
          format: int64
          type: integer
           
      type: object   
    NoteRsModel:
      description: Contains all the data for note creation.
      properties:
        noteId:
          format: int64
          type: integer
        content:
          type: string
        createdBy:
          format: int64
          type: integer
        signature:
          type: string
        fileId:
          format: int64
          type: integer
        fileMovementId:
          format: int64
          type: integer
        hasYellowNote:
          type: boolean
  
      type: object    
    NoteDocumentRsModel:
      description: Contains all the data for note Document creation.
      properties:
        noteDocumentId:
          format: int64
          type: integer
        noteDocumentNumber:
          type: string
        subject:
          type: string
        createdBy:
          format: int64
          type: integer
        subjectCategoryId:
           format: int64
           type: integer
        createDate:
            type: string
        modifiedDate:
            type: string
          
      type: object 
      
paths:
  /createFile:
    post:
      operationId: createFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FileRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/FileRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
          description: ''
      tags: ["FileRsModel"]
  
  /updateDocFile:
    put:
      operationId: updateDocFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FileRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/FileRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
          description: ''
      tags: ["FileRsModel"]
      
  /createReceipt:
    post:
      operationId: createReceipt
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReceiptRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/ReceiptRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ReceiptRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/ReceiptRsModel'
          description: ''
      tags: ["ReceiptRsModel"]
  /receiptId/{receiptId}:
    get:
      operationId: getReceiptByReceiptId
      parameters:
        - in: path
          name: receiptId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ReceiptRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/ReceiptRsModel'
          description: ''
      tags: ["ReceiptRsModel"]
  /updateReceipt:
    put:
      operationId: updateReceipt
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReceiptRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/ReceiptRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ReceiptRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/ReceiptRsModel'
          description: ''
      tags: ["ReceiptRsModel"]
  /createNote:
    post:
      operationId: createNote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/NoteRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/NoteRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/NoteRsModel'
          description: ''
      tags: ["NoteRsModel"] 
  /editNote:
    put:
      operationId: editNote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/NoteRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/NoteRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/NoteRsModel'
          description: ''
      tags: ["NoteRsModel"] 
  /deleteNote/{noteId}:
    post:
      operationId: deleteNote
      parameters:
        - in: path
          name: noteId
          schema:
            type: integer
            format: int64
          required: true
          description: noteId to delete note.
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
      tags: ["NoteRsModel"]   
      
  /updateNoteDocument:
    put:
      operationId: updateNoteDocument
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteDocumentRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/NoteDocumentRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/NoteDocumentRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/NoteDocumentRsModel'
          description: ''
      tags: ["NoteDocumentRsModel"]
      
  /createNoteDocument:
    post:
      operationId: createNoteDocument
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteDocumentRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/NoteDocumentRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/NoteDocumentRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/NoteDocumentRsModel'
          description: ''
      tags: ["NoteDocumentRsModel"]
 
      