/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.masterdata.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Masterdata service. Represents a row in the &quot;Masterdata_Masterdata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.masterdata.model.impl.MasterdataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.masterdata.model.impl.MasterdataImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Masterdata
 * @generated
 */
@ProviderType
public interface MasterdataModel extends BaseModel<Masterdata> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a masterdata model instance should use the {@link Masterdata} interface instead.
	 */

	/**
	 * Returns the primary key of this masterdata.
	 *
	 * @return the primary key of this masterdata
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this masterdata.
	 *
	 * @param primaryKey the primary key of this masterdata
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the masterdata ID of this masterdata.
	 *
	 * @return the masterdata ID of this masterdata
	 */
	@AutoEscape
	public String getMasterdataId();

	/**
	 * Sets the masterdata ID of this masterdata.
	 *
	 * @param masterdataId the masterdata ID of this masterdata
	 */
	public void setMasterdataId(String masterdataId);

	/**
	 * Returns the reference ID of this masterdata.
	 *
	 * @return the reference ID of this masterdata
	 */
	@AutoEscape
	public String getReferenceId();

	/**
	 * Sets the reference ID of this masterdata.
	 *
	 * @param referenceId the reference ID of this masterdata
	 */
	public void setReferenceId(String referenceId);

	/**
	 * Returns the value of this masterdata.
	 *
	 * @return the value of this masterdata
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this masterdata.
	 *
	 * @param value the value of this masterdata
	 */
	public void setValue(String value);

	/**
	 * Returns the code of this masterdata.
	 *
	 * @return the code of this masterdata
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this masterdata.
	 *
	 * @param code the code of this masterdata
	 */
	public void setCode(String code);

	@Override
	public Masterdata cloneWithOriginalValues();

}