/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FileMovement service. Represents a row in the &quot;JET_PROCESS_FileMovement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.FileMovementModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.FileMovementImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileMovement
 * @generated
 */
@ProviderType
public interface FileMovementModel
	extends BaseModel<FileMovement>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file movement model instance should use the {@link FileMovement} interface instead.
	 */

	/**
	 * Returns the primary key of this file movement.
	 *
	 * @return the primary key of this file movement
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file movement.
	 *
	 * @param primaryKey the primary key of this file movement
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this file movement.
	 *
	 * @return the uuid of this file movement
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this file movement.
	 *
	 * @param uuid the uuid of this file movement
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the fm ID of this file movement.
	 *
	 * @return the fm ID of this file movement
	 */
	public long getFmId();

	/**
	 * Sets the fm ID of this file movement.
	 *
	 * @param fmId the fm ID of this file movement
	 */
	public void setFmId(long fmId);

	/**
	 * Returns the group ID of this file movement.
	 *
	 * @return the group ID of this file movement
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this file movement.
	 *
	 * @param groupId the group ID of this file movement
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this file movement.
	 *
	 * @return the company ID of this file movement
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this file movement.
	 *
	 * @param companyId the company ID of this file movement
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this file movement.
	 *
	 * @return the user ID of this file movement
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this file movement.
	 *
	 * @param userId the user ID of this file movement
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this file movement.
	 *
	 * @return the user uuid of this file movement
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this file movement.
	 *
	 * @param userUuid the user uuid of this file movement
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this file movement.
	 *
	 * @return the create date of this file movement
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this file movement.
	 *
	 * @param createDate the create date of this file movement
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this file movement.
	 *
	 * @return the modified date of this file movement
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this file movement.
	 *
	 * @param modifiedDate the modified date of this file movement
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the receiver ID of this file movement.
	 *
	 * @return the receiver ID of this file movement
	 */
	public long getReceiverId();

	/**
	 * Sets the receiver ID of this file movement.
	 *
	 * @param receiverId the receiver ID of this file movement
	 */
	public void setReceiverId(long receiverId);

	/**
	 * Returns the sender ID of this file movement.
	 *
	 * @return the sender ID of this file movement
	 */
	public long getSenderId();

	/**
	 * Sets the sender ID of this file movement.
	 *
	 * @param senderId the sender ID of this file movement
	 */
	public void setSenderId(long senderId);

	/**
	 * Returns the file ID of this file movement.
	 *
	 * @return the file ID of this file movement
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this file movement.
	 *
	 * @param fileId the file ID of this file movement
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the priority of this file movement.
	 *
	 * @return the priority of this file movement
	 */
	@AutoEscape
	public String getPriority();

	/**
	 * Sets the priority of this file movement.
	 *
	 * @param priority the priority of this file movement
	 */
	public void setPriority(String priority);

	/**
	 * Returns the due date of this file movement.
	 *
	 * @return the due date of this file movement
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this file movement.
	 *
	 * @param dueDate the due date of this file movement
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the remark of this file movement.
	 *
	 * @return the remark of this file movement
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this file movement.
	 *
	 * @param remark the remark of this file movement
	 */
	public void setRemark(String remark);

	/**
	 * Returns the read on of this file movement.
	 *
	 * @return the read on of this file movement
	 */
	@AutoEscape
	public String getReadOn();

	/**
	 * Sets the read on of this file movement.
	 *
	 * @param readOn the read on of this file movement
	 */
	public void setReadOn(String readOn);

	/**
	 * Returns the received on of this file movement.
	 *
	 * @return the received on of this file movement
	 */
	@AutoEscape
	public String getReceivedOn();

	/**
	 * Sets the received on of this file movement.
	 *
	 * @param receivedOn the received on of this file movement
	 */
	public void setReceivedOn(String receivedOn);

	/**
	 * Returns the pull back remark of this file movement.
	 *
	 * @return the pull back remark of this file movement
	 */
	@AutoEscape
	public String getPullBackRemark();

	/**
	 * Sets the pull back remark of this file movement.
	 *
	 * @param pullBackRemark the pull back remark of this file movement
	 */
	public void setPullBackRemark(String pullBackRemark);

	/**
	 * Returns the active of this file movement.
	 *
	 * @return the active of this file movement
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this file movement is active.
	 *
	 * @return <code>true</code> if this file movement is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this file movement is active.
	 *
	 * @param active the active of this file movement
	 */
	public void setActive(boolean active);

	/**
	 * Returns the movement type of this file movement.
	 *
	 * @return the movement type of this file movement
	 */
	public long getMovementType();

	/**
	 * Sets the movement type of this file movement.
	 *
	 * @param movementType the movement type of this file movement
	 */
	public void setMovementType(long movementType);

	@Override
	public FileMovement cloneWithOriginalValues();

}