/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FileCorr service. Represents a row in the &quot;JET_PROCESS_FileCorr&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.FileCorrModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.FileCorrImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileCorr
 * @generated
 */
@ProviderType
public interface FileCorrModel
	extends BaseModel<FileCorr>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file corr model instance should use the {@link FileCorr} interface instead.
	 */

	/**
	 * Returns the primary key of this file corr.
	 *
	 * @return the primary key of this file corr
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file corr.
	 *
	 * @param primaryKey the primary key of this file corr
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this file corr.
	 *
	 * @return the uuid of this file corr
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this file corr.
	 *
	 * @param uuid the uuid of this file corr
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the file corr ID of this file corr.
	 *
	 * @return the file corr ID of this file corr
	 */
	public long getFileCorrId();

	/**
	 * Sets the file corr ID of this file corr.
	 *
	 * @param fileCorrId the file corr ID of this file corr
	 */
	public void setFileCorrId(long fileCorrId);

	/**
	 * Returns the group ID of this file corr.
	 *
	 * @return the group ID of this file corr
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this file corr.
	 *
	 * @param groupId the group ID of this file corr
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this file corr.
	 *
	 * @return the company ID of this file corr
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this file corr.
	 *
	 * @param companyId the company ID of this file corr
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this file corr.
	 *
	 * @return the user ID of this file corr
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this file corr.
	 *
	 * @param userId the user ID of this file corr
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this file corr.
	 *
	 * @return the user uuid of this file corr
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this file corr.
	 *
	 * @param userUuid the user uuid of this file corr
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this file corr.
	 *
	 * @return the create date of this file corr
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this file corr.
	 *
	 * @param createDate the create date of this file corr
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this file corr.
	 *
	 * @return the modified date of this file corr
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this file corr.
	 *
	 * @param modifiedDate the modified date of this file corr
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the doc file ID of this file corr.
	 *
	 * @return the doc file ID of this file corr
	 */
	public long getDocFileId();

	/**
	 * Sets the doc file ID of this file corr.
	 *
	 * @param docFileId the doc file ID of this file corr
	 */
	public void setDocFileId(long docFileId);

	/**
	 * Returns the receipt ID of this file corr.
	 *
	 * @return the receipt ID of this file corr
	 */
	public long getReceiptId();

	/**
	 * Sets the receipt ID of this file corr.
	 *
	 * @param receiptId the receipt ID of this file corr
	 */
	public void setReceiptId(long receiptId);

	/**
	 * Returns the user post ID of this file corr.
	 *
	 * @return the user post ID of this file corr
	 */
	public long getUserPostId();

	/**
	 * Sets the user post ID of this file corr.
	 *
	 * @param userPostId the user post ID of this file corr
	 */
	public void setUserPostId(long userPostId);

	/**
	 * Returns the correspondence type of this file corr.
	 *
	 * @return the correspondence type of this file corr
	 */
	@AutoEscape
	public String getCorrespondenceType();

	/**
	 * Sets the correspondence type of this file corr.
	 *
	 * @param correspondenceType the correspondence type of this file corr
	 */
	public void setCorrespondenceType(String correspondenceType);

	/**
	 * Returns the remarks of this file corr.
	 *
	 * @return the remarks of this file corr
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this file corr.
	 *
	 * @param remarks the remarks of this file corr
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the file movement ID of this file corr.
	 *
	 * @return the file movement ID of this file corr
	 */
	public long getFileMovementId();

	/**
	 * Sets the file movement ID of this file corr.
	 *
	 * @param fileMovementId the file movement ID of this file corr
	 */
	public void setFileMovementId(long fileMovementId);

	/**
	 * Returns the receipt movement ID of this file corr.
	 *
	 * @return the receipt movement ID of this file corr
	 */
	public long getReceiptMovementId();

	/**
	 * Sets the receipt movement ID of this file corr.
	 *
	 * @param receiptMovementId the receipt movement ID of this file corr
	 */
	public void setReceiptMovementId(long receiptMovementId);

	@Override
	public FileCorr cloneWithOriginalValues();

}