/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FileNote service. Represents a row in the &quot;JET_PROCESS_FileNote&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.FileNoteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.FileNoteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileNote
 * @generated
 */
@ProviderType
public interface FileNoteModel
	extends BaseModel<FileNote>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file note model instance should use the {@link FileNote} interface instead.
	 */

	/**
	 * Returns the primary key of this file note.
	 *
	 * @return the primary key of this file note
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file note.
	 *
	 * @param primaryKey the primary key of this file note
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this file note.
	 *
	 * @return the uuid of this file note
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this file note.
	 *
	 * @param uuid the uuid of this file note
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the file note ID of this file note.
	 *
	 * @return the file note ID of this file note
	 */
	public long getFileNoteId();

	/**
	 * Sets the file note ID of this file note.
	 *
	 * @param fileNoteId the file note ID of this file note
	 */
	public void setFileNoteId(long fileNoteId);

	/**
	 * Returns the group ID of this file note.
	 *
	 * @return the group ID of this file note
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this file note.
	 *
	 * @param groupId the group ID of this file note
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this file note.
	 *
	 * @return the company ID of this file note
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this file note.
	 *
	 * @param companyId the company ID of this file note
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this file note.
	 *
	 * @return the user ID of this file note
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this file note.
	 *
	 * @param userId the user ID of this file note
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this file note.
	 *
	 * @return the user uuid of this file note
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this file note.
	 *
	 * @param userUuid the user uuid of this file note
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this file note.
	 *
	 * @return the user name of this file note
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this file note.
	 *
	 * @param userName the user name of this file note
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this file note.
	 *
	 * @return the create date of this file note
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this file note.
	 *
	 * @param createDate the create date of this file note
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this file note.
	 *
	 * @return the modified date of this file note
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this file note.
	 *
	 * @param modifiedDate the modified date of this file note
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the file ID of this file note.
	 *
	 * @return the file ID of this file note
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this file note.
	 *
	 * @param fileId the file ID of this file note
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the file movement ID of this file note.
	 *
	 * @return the file movement ID of this file note
	 */
	public long getFileMovementId();

	/**
	 * Sets the file movement ID of this file note.
	 *
	 * @param fileMovementId the file movement ID of this file note
	 */
	public void setFileMovementId(long fileMovementId);

	/**
	 * Returns the note ID of this file note.
	 *
	 * @return the note ID of this file note
	 */
	public long getNoteId();

	/**
	 * Sets the note ID of this file note.
	 *
	 * @param noteId the note ID of this file note
	 */
	public void setNoteId(long noteId);

	/**
	 * Returns the movement type of this file note.
	 *
	 * @return the movement type of this file note
	 */
	public long getMovementType();

	/**
	 * Sets the movement type of this file note.
	 *
	 * @param movementType the movement type of this file note
	 */
	public void setMovementType(long movementType);

	@Override
	public FileNote cloneWithOriginalValues();

}