/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NoteDocMovement service. Represents a row in the &quot;JET_PROCESS_NoteDocMovement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.NoteDocMovementModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.NoteDocMovementImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NoteDocMovement
 * @generated
 */
@ProviderType
public interface NoteDocMovementModel
	extends BaseModel<NoteDocMovement>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a note doc movement model instance should use the {@link NoteDocMovement} interface instead.
	 */

	/**
	 * Returns the primary key of this note doc movement.
	 *
	 * @return the primary key of this note doc movement
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this note doc movement.
	 *
	 * @param primaryKey the primary key of this note doc movement
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this note doc movement.
	 *
	 * @return the uuid of this note doc movement
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this note doc movement.
	 *
	 * @param uuid the uuid of this note doc movement
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the movement ID of this note doc movement.
	 *
	 * @return the movement ID of this note doc movement
	 */
	public long getMovementId();

	/**
	 * Sets the movement ID of this note doc movement.
	 *
	 * @param movementId the movement ID of this note doc movement
	 */
	public void setMovementId(long movementId);

	/**
	 * Returns the group ID of this note doc movement.
	 *
	 * @return the group ID of this note doc movement
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this note doc movement.
	 *
	 * @param groupId the group ID of this note doc movement
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this note doc movement.
	 *
	 * @return the company ID of this note doc movement
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this note doc movement.
	 *
	 * @param companyId the company ID of this note doc movement
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this note doc movement.
	 *
	 * @return the user ID of this note doc movement
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this note doc movement.
	 *
	 * @param userId the user ID of this note doc movement
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this note doc movement.
	 *
	 * @return the user uuid of this note doc movement
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this note doc movement.
	 *
	 * @param userUuid the user uuid of this note doc movement
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this note doc movement.
	 *
	 * @return the user name of this note doc movement
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this note doc movement.
	 *
	 * @param userName the user name of this note doc movement
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this note doc movement.
	 *
	 * @return the create date of this note doc movement
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this note doc movement.
	 *
	 * @param createDate the create date of this note doc movement
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this note doc movement.
	 *
	 * @return the modified date of this note doc movement
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this note doc movement.
	 *
	 * @param modifiedDate the modified date of this note doc movement
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the receiver ID of this note doc movement.
	 *
	 * @return the receiver ID of this note doc movement
	 */
	public long getReceiverId();

	/**
	 * Sets the receiver ID of this note doc movement.
	 *
	 * @param receiverId the receiver ID of this note doc movement
	 */
	public void setReceiverId(long receiverId);

	/**
	 * Returns the sender ID of this note doc movement.
	 *
	 * @return the sender ID of this note doc movement
	 */
	public long getSenderId();

	/**
	 * Sets the sender ID of this note doc movement.
	 *
	 * @param senderId the sender ID of this note doc movement
	 */
	public void setSenderId(long senderId);

	/**
	 * Returns the note document ID of this note doc movement.
	 *
	 * @return the note document ID of this note doc movement
	 */
	public long getNoteDocumentId();

	/**
	 * Sets the note document ID of this note doc movement.
	 *
	 * @param noteDocumentId the note document ID of this note doc movement
	 */
	public void setNoteDocumentId(long noteDocumentId);

	/**
	 * Returns the remarks of this note doc movement.
	 *
	 * @return the remarks of this note doc movement
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this note doc movement.
	 *
	 * @param remarks the remarks of this note doc movement
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the active of this note doc movement.
	 *
	 * @return the active of this note doc movement
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this note doc movement is active.
	 *
	 * @return <code>true</code> if this note doc movement is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this note doc movement is active.
	 *
	 * @param active the active of this note doc movement
	 */
	public void setActive(boolean active);

	/**
	 * Returns the movement type of this note doc movement.
	 *
	 * @return the movement type of this note doc movement
	 */
	public long getMovementType();

	/**
	 * Sets the movement type of this note doc movement.
	 *
	 * @param movementType the movement type of this note doc movement
	 */
	public void setMovementType(long movementType);

	@Override
	public NoteDocMovement cloneWithOriginalValues();

}