/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NoteDocument service. Represents a row in the &quot;JET_PROCESS_NoteDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.NoteDocumentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.NoteDocumentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NoteDocument
 * @generated
 */
@ProviderType
public interface NoteDocumentModel
	extends BaseModel<NoteDocument>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a note document model instance should use the {@link NoteDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this note document.
	 *
	 * @return the primary key of this note document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this note document.
	 *
	 * @param primaryKey the primary key of this note document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this note document.
	 *
	 * @return the uuid of this note document
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this note document.
	 *
	 * @param uuid the uuid of this note document
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the note document ID of this note document.
	 *
	 * @return the note document ID of this note document
	 */
	public long getNoteDocumentId();

	/**
	 * Sets the note document ID of this note document.
	 *
	 * @param noteDocumentId the note document ID of this note document
	 */
	public void setNoteDocumentId(long noteDocumentId);

	/**
	 * Returns the group ID of this note document.
	 *
	 * @return the group ID of this note document
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this note document.
	 *
	 * @param groupId the group ID of this note document
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this note document.
	 *
	 * @return the company ID of this note document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this note document.
	 *
	 * @param companyId the company ID of this note document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this note document.
	 *
	 * @return the user ID of this note document
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this note document.
	 *
	 * @param userId the user ID of this note document
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this note document.
	 *
	 * @return the user uuid of this note document
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this note document.
	 *
	 * @param userUuid the user uuid of this note document
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this note document.
	 *
	 * @return the user name of this note document
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this note document.
	 *
	 * @param userName the user name of this note document
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this note document.
	 *
	 * @return the create date of this note document
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this note document.
	 *
	 * @param createDate the create date of this note document
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this note document.
	 *
	 * @return the modified date of this note document
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this note document.
	 *
	 * @param modifiedDate the modified date of this note document
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the note document number of this note document.
	 *
	 * @return the note document number of this note document
	 */
	@AutoEscape
	public String getNoteDocumentNumber();

	/**
	 * Sets the note document number of this note document.
	 *
	 * @param noteDocumentNumber the note document number of this note document
	 */
	public void setNoteDocumentNumber(String noteDocumentNumber);

	/**
	 * Returns the subject of this note document.
	 *
	 * @return the subject of this note document
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this note document.
	 *
	 * @param subject the subject of this note document
	 */
	public void setSubject(String subject);

	/**
	 * Returns the created by of this note document.
	 *
	 * @return the created by of this note document
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this note document.
	 *
	 * @param createdBy the created by of this note document
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the subject category ID of this note document.
	 *
	 * @return the subject category ID of this note document
	 */
	public long getSubjectCategoryId();

	/**
	 * Sets the subject category ID of this note document.
	 *
	 * @param subjectCategoryId the subject category ID of this note document
	 */
	public void setSubjectCategoryId(long subjectCategoryId);

	/**
	 * Returns the currently with of this note document.
	 *
	 * @return the currently with of this note document
	 */
	public long getCurrentlyWith();

	/**
	 * Sets the currently with of this note document.
	 *
	 * @param currentlyWith the currently with of this note document
	 */
	public void setCurrentlyWith(long currentlyWith);

	/**
	 * Returns the current state of this note document.
	 *
	 * @return the current state of this note document
	 */
	public int getCurrentState();

	/**
	 * Sets the current state of this note document.
	 *
	 * @param currentState the current state of this note document
	 */
	public void setCurrentState(int currentState);

	@Override
	public NoteDocument cloneWithOriginalValues();

}