apiDir: "../jet-process-docs-api/src/main/java"
apiPackagePath: "io.jetprocess.docs"
application:
    baseURI: "/jet-process-docs"
    className: "JetProcessDocsApplication"
    name: "JetProcessDocs"
author: "Admin"